//created on: Aug 21, 2016
package com.cmx.intelix

//list any import classes here.
import com.cmx.intelix.Person
import com.cmx.intelix.Errors
import com.cmx.intelix.Error



//declare any global variables here




rule "Age should be greater than 18"

    when
        //conditions.
        $p : Person( age < 18 )
        $errors : Errors(  )
    then
        //actions
        $errors.addError( $p, "age", "Person age shpuld not be less than 18" );

end

